version: "3.8"

services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
        environment:
            - DATABASE_URL=postgres://$DB_USER:$DB_PASSWORD@pgdb:5432/$DB_NAME
            - DJANGO_ENV=docker-desktop
        networks:
            - monreseau

    pgdb:
        image: postgres:latest
        container_name: pgdb
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - monreseau

volumes:
    pgdata_data:

networks:
    monreseau:


